### ISSUE TITLE
Event time timeout with flatMapGroupsWithState

### ISSUE THREAD

**Issue by aandis** [chermenin/spark-states#16]
Are state timeouts supported based on [event time timeout](https://spark.apache.org/docs/latest/api/java/org/apache/spark/sql/streaming/GroupStateTimeout.html#EventTimeTimeout--) when using flatMapGroupsWithState?

**Comment by chitralverma** [comment]
Spark States bypasses Spark's `flatMapGroupsWithState` and `mapGroupsWithState` API for all its actions by directly manipulating the state stores. So no, they are not supported.
However, when using this library, you technically do need to use `flatMapGroupsWithState` any more as your usual spark job will work in a stateful/ stateless manner as long as the right options are set. 

Are you running into any issues?

**Comment by aandis** [comment]
I need to use `flatMapGroupsWithState` for some complex aggregation and expire state based on event time. I used this library and was expecting to run into an error since the [documentation](https://github.com/chermenin/spark-states#state-timeout) only says processing time timeouts are supported but I did not see any issues. So I'm wondering what is the expected behavior if event time timeouts are configured while using this lib?

**Comment by chitralverma** [comment]
So, regarding the support for `EventTimeTimeout`, well it's definitely on my agenda but it may take a while. Currently, it's not supported at all in the sense that this library is oblivious to event time. 
If you are using `flatMapGroupsWithState`, this library will not affect timeouts in any way (for processing time and event time), that's why you are not getting any errors and this is expected since this library handles states differently.
However, I will also advise you to not use spark-states and `flatMapGroupsWithState`/ `mapGroupsWithState` together in a job as it may lead to unexpected results in your resultant dataframe(s). This library is supposed to be more of an alternative of `flatMapGroupsWithState`/ `mapGroupsWithState`.

**Comment by aandis** [comment]
Thanks for the info. Support for event time based timeout would be pretty cool. 

> This library is supposed to be more of an alternative of flatMapGroupsWithState/ mapGroupsWithState.

My understanding of this library was that it would store the state in rocksdb for stateful aggregations which is much more efficient. groupWithState based aggregations allow you to do arbitrary stateful aggregations. I don't understand what you mean by this library being a replacement for that.

**Comment by chitralverma** [comment]
> My understanding of this library was that it would store the state in rocksdb for stateful aggregations which is much more efficient. 

Yes, this is correct.

>groupWithState based aggregations allow you to do arbitrary stateful aggregations. I don't understand what you mean by this library being a replacement for that.

I meant that you can still do complex stateful/ stateless aggregations without using the `groupWithState` functions, if you are using this library, you can simply omit the `groupWithState` functions.

For example, with `mapGroupsWithState` API you will do something like this,
```
def updateStateFunctions(user:String,
    inputs: Iterator[InputRow],
     oldState: GroupState[UserState]):UserState = ???

val finishedUserSessionsStream: Dataset[UserSession] = userEventsStream
    .map(deserializeUserEvent)
    .groupByKey(_.id)
    .mapGroupsWithState(GroupStateTimeout.ProcessingTimeTimeout())(updateStateFunctions)
    .flatMap(userSession => userSession)

finishedUserSessionsStream.writeStream
  .outputMode(OutputMode.Update())
  .format("console")
  .option("checkpointLocation", "hdfs:///path/to/checkpoint/location")
  .start()
  .awaitTermination()
```

If you're using `spark-states` it will be something like,

```
import ru.chermenin.spark.sql.execution.streaming.state.implicits._

val finishedUserSessionsStream: Dataset[UserSession] = userEventsStream
    .map(deserializeUserEvent)
    .groupBy(col("id"))
    .agg(???)

finishedUserSessionsStream.writeStream
  .outputMode(OutputMode.Update())
  .format("console")
  .trigger(Trigger.ProcessingTime(1000L))
  .stateTimeout(spark.conf, queryName="myQuery1", expirySecs = 5, checkpointLocation ="hdfs:///path/to/checkpoint/location")
  .start()
  .awaitTermination()
```


The example might not be 100% exact but hopefully, this will show the difference.

Additionally, since `groupWithState` functions are not required with this library, you also have the liberty to heavily use the 100s of `org.apache.spark.sql.functions` instead of manually implementing them when using `groupWithState` functions.
